In [1]:
# The network:
weight = 0.1

def neural_network(input, weight):
    prediction = input * weight
    return prediction

# How we use the network to predict something:

number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]
pred = neural_network(input, weight)
print(pred)

0.8500000000000001


### Прогнозирование с несколькими входами

In [1]:
def w_sum(input, weights):
    assert (len(input) == len(weights))
    output = 0
    for i in range(len(input)):
        output += (input[i] * weights[i])
    return output

def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred

# This dataset is the current
# status at the beginning of
# each game for the first 4 games
# in a season.

weights = [0.1, 0.2, 0]  
# 0.1 for toes
# 0.2 for wlrec
# 0 for nfans

# toes = average count of games
# wlrec = current games won (percent)
# nfans = fan count (in millions)

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

# Input corresponds to every entry
# for the first game of the season.

inputs = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(inputs, weights)

print(pred)

0.9800000000000001


### NumPy Code

In [2]:
import numpy as np

# .dot - dot product (скалярное произведение)
# .dot зи NumPy заменяет w_sum из кода выше

def neural_network(input, weights):
    pred = input.dot(weights)
    return pred

weights = np.array([0.1, 0.2, 0])

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

# Input corresponds to every entry
# for the first game of the season.

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)

print(pred)

0.9800000000000001


### Прогнозирование с несколькими выходами

In [3]:
# Instead of predicting just
# whether the team won or lost,
# now we're also predicting whether
# they are happy/sad AND the percentage
# of the team that is hurt. We are
# making this prediction using only
# the current win/loss record.

def ele_mul(number, vector):
    output = [0, 0, 0]
    assert (len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

def neural_network(input, weights):
    pred = ele_mul(input, weights)
    return pred

weights = [0.3, 0.2, 0.9] #  [hurt, win, happy]

wlrec = [0.65, 0.8, 0.8, 0.9]
# wlrec = current games won (percent)

pred = neural_network(wlrec[0], weights)

print(pred)

[0.195, 0.13, 0.5850000000000001]


### Прогнозироваие с несколькими входами и выходами

In [10]:
def w_sum(vector, matrix):
    assert (len(vector) == len(matrix))
    output = 0
    for i in range(len(vector)):
        output += (vector[i] * matrix[i])
    return output

def vect_mat_mul(input_vector, weights_matrix):
    assert (len(input_vector) == len(weights_matrix))
    output = [0, 0, 0]
    for i in range(len(input_vector)):
        output[i] = w_sum(input_vector, weights_matrix[i])
    return output

def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred

hurt = [0.1, 0.1, -0.3]
win = [0.1, 0.2, 0.0]
sad = [0.0, 1.3, 0.1]

weights = [hurt, win, sad]

# This dataset is the current
# status at the beginning of
# each game for the first 4 games
# in a season

# toes = current number of toes (среднее число игр, сыграных игроками)
toes = [8.5, 9.5, 9.9, 9.0]
# wlrec = current games won (percent)
wlrec = [0.65, 0.8, 0.8, 0.9]
# nfans = fan count (in millions)
nfans = [1.2, 1.3, 0.5, 1.0]

# Input corresponds to every entry
# for the first game of the season.

input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)

#   toes          %win           #fans
#  (8.5 * 0.1) + (0.65 * 0.1) + (1.2 * -0.3) = 0.555 # hurt?
#  (8.5 * 0.1) + (0.65 * 0.2) + (1.2 * 0.0) = 0.98   # win?
#  (8.5 * 0.0) + (0.65 * 1.3) + (1.2 * 0.1) = 0.965  # sad?

print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


### Прогнозирование на основе прогнозов

In [12]:
         # toes %win #fans
ih_wgt = [[0.1, 0.2, -0.1],  # hid[0]
          [-0.1, 0.1, 0.9],  # hid[1]
          [0.1, 0.4, 0.1]]   # hid[2]

#       hid[0] hid[1] hid[2]
hp_wgt = [[0.3, 1.1, -0.3], # hurt?
          [0.1, 0.2, 0.0],  # win?
          [0.0, 1.3, 0.1]]  # sad?

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = vect_mat_mul(input, weights[0]) # hidden layer
    pred = vect_mat_mul(hid, weights[1])
    return pred

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

# Input corresponds to every entry
# for the first game of the season.

input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)

print(pred)

[0.21350000000000002, 0.14500000000000002, 0.5065]


### Версия с NumPy

In [17]:
import numpy as np

# toes %win #fans
ih_wgt = np.array([
    [0.1, 0.2, -0.1],  # hid[0]
    [-0.1, 0.1, 0.9],  # hid[1]
    [0.1, 0.4, 0.1]]).T  # hid[2]


# hid[0] hid[1] hid[2]
hp_wgt = np.array([
    [0.3, 1.1, -0.3],  # hurt?
    [0.1, 0.2, 0.0],  # win?
    [0.0, 1.3, 0.1]]).T  # sad?

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])

pred = neural_network(input, weights)
print(pred)

[0.2135 0.145  0.5065]


### Короткий пример NumPy

In [21]:
import numpy as np

vector_a = np.array([0, 1, 2, 3])  # a vector
vector_b = np.array([4, 5, 6, 7])  # another vector
matrix_c = np.array([[0, 1, 2, 3],  # a matrix
              [4, 5, 6, 7]])

zeros_d = np.zeros((2, 4))  # (2x4 matrix of zeros)
random_e = np.random.rand(2, 5)  # random 2x5
# matrix with all numbers between 0 and 1

print(vector_a)
print(vector_b)
print(matrix_c)
print(zeros_d)
print(random_e)

print("=============================")

print(vector_a * 0.1)  # multiplies every number in vector "a" by 0.1

print(matrix_c * 0.2)  # multiplies every number in matrix "c" by 0.2
# multiplies elementwise between a and b (columns paired up)
print(vector_a * vector_b)  
# [0, 1, 2, 3] * [4, 5, 6, 7] = [0, 5, 12, 21]

# elementwise multiplication then multiplied by 0.2
print(vector_a * vector_b * 0.2)
# [0, 1, 2, 3] * [4, 5, 6, 7] * 0.2 = [0.0, 1.0, 2.4, 4.2]

# since c has the same number of columns as a, this performs
# elementwise multiplication on every row of the matrix "c"
print(vector_a * matrix_c)
# [0, 1, 2, 3] * [[0, 1, 2, 3],
#                 [4, 5, 6, 7]] = [[0, 1, 4, 9], [0, 5, 12, 21]]

# since a and e don't have the same number of columns, this
# throws a "Value Error: operands could not be broadcast together with.."
print(vector_a * random_e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.22504302 0.83799818 0.28320111 0.07299095 0.95277288]
 [0.12406373 0.08213084 0.30025    0.71062728 0.30054102]]
[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]


ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

# (rows, cols)

### .dot - dot product (скалярное произведение)

Число столбцов в матрице слева должно совпадать с числом строк в матрице справа.
`(a,b).dot(b,c) = (a,c)`

In [27]:
a = np.zeros((1, 4))  # vector of length 4
b = np.zeros((4, 3))  # matrix with 4 rows & 3 columns

print(a.dot(b).shape)  # (1, 3)
# print(b.dot(a).shape)  # ValueError Traceback (most recent call last)

(1, 3)


In [28]:
a = np.zeros((2, 4))  # matrix with 2 rows and 4 columns
b = np.zeros((4, 3))  # matrix with 4 rows & 3 columns

c = a.dot(b)
print(c.shape)  # outputs (2,3)

e = np.zeros((2, 1))  # matrix with 2 rows and 1 columns
f = np.zeros((1, 3))  # matrix with 1 row & 3 columns

g = e.dot(f)
print(g.shape)  # outputs (2,3)

h = np.zeros((5, 4)).T  # matrix with 4 rows and 5 columns
i = np.zeros((5, 6))  # matrix with 6 rows & 5 columns

j = h.dot(i)
print(j.shape)  # outputs (4,6)

h = np.zeros((5, 4))  # matrix with 5 rows and 4 columns
i = np.zeros((5, 6))  # matrix with 5 rows & 6 columns
j = h.dot(i)
print(j.shape)  # ValueError j = h.dot(i)

(2, 3)
(2, 3)
(4, 6)


ValueError: shapes (5,4) and (5,6) not aligned: 4 (dim 1) != 5 (dim 0)

### Прогнозирующие возможности сети зависят отзначений весов.

Все сети которые тут созданы называются сетями прямого распространения - принимают входные данные и получают прогноз.